name: e2e

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "15.12.0"

      - run: npm install  --registry=https://registry.npmjs.org
      - name: Running mongodb service
        run: |
          docker-compose up -d mongodb
          docker ps -a
      # install dependencies and build the project
      - name: Running e2e testing
        run: |
          npm run test:e2e -- --runInBand --forceExit
